// Auto-generated by: supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.types.ts
// Replace this file by running that command after connecting your Supabase project.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

type UserRole = 'super_admin' | 'admin' | 'support_staff' | 'tailor_master' | 'tailor' | 'embroidery_staff'
type OrderStatus = 'draft' | 'confirmed' | 'assigned' | 'in_tailoring' | 'in_embroidery' | 'quality_check' | 'ready' | 'delivered' | 'cancelled'
type ProductType = 'scrubs' | 'apron' | 'head_cap' | 'card_holder'
type MediaType = 'image' | 'video' | 'voice_note' | 'document'
type NotificationType = 'order_created' | 'order_status_changed' | 'order_assigned' | 'order_ready' | 'order_delivered' | 'embroidery_requested' | 'quality_check_failed' | 'mention'

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string
          phone: string | null
          role: UserRole
          avatar_url: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name: string
          phone?: string | null
          role?: UserRole
          avatar_url?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string
          phone?: string | null
          role?: UserRole
          avatar_url?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      customers: {
        Row: {
          id: string
          full_name: string
          phone: string
          phone_alt: string | null
          email: string | null
          organization: string | null
          address: string | null
          notes: string | null
          phone_normalized: string
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          full_name: string
          phone: string
          phone_alt?: string | null
          email?: string | null
          organization?: string | null
          address?: string | null
          notes?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          phone?: string
          phone_alt?: string | null
          email?: string | null
          organization?: string | null
          address?: string | null
          notes?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      orders: {
        Row: {
          id: string
          order_number: string
          customer_id: string
          status: OrderStatus
          priority: number
          delivery_date: string | null
          total_items: number
          special_instructions: string | null
          notes: string | null
          ai_intake_used: boolean
          ai_transcript: string | null
          ai_confidence: number | null
          created_by: string
          confirmed_by: string | null
          confirmed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_number?: string
          customer_id: string
          status?: OrderStatus
          priority?: number
          delivery_date?: string | null
          total_items?: number
          special_instructions?: string | null
          notes?: string | null
          ai_intake_used?: boolean
          ai_transcript?: string | null
          ai_confidence?: number | null
          created_by: string
          confirmed_by?: string | null
          confirmed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_number?: string
          customer_id?: string
          status?: OrderStatus
          priority?: number
          delivery_date?: string | null
          total_items?: number
          special_instructions?: string | null
          notes?: string | null
          ai_intake_used?: boolean
          ai_transcript?: string | null
          ai_confidence?: number | null
          created_by?: string
          confirmed_by?: string | null
          confirmed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          sequence_number: number
          product_type: ProductType
          quantity: number
          color: string | null
          piping_color: string | null
          design_config: Json
          has_embroidery: boolean
          embroidery_name: string | null
          embroidery_logo_url: string | null
          special_instructions: string | null
          status: OrderStatus
          unit_price: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          sequence_number: number
          product_type: ProductType
          quantity?: number
          color?: string | null
          piping_color?: string | null
          design_config?: Json
          has_embroidery?: boolean
          embroidery_name?: string | null
          embroidery_logo_url?: string | null
          special_instructions?: string | null
          status?: OrderStatus
          unit_price?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          sequence_number?: number
          product_type?: ProductType
          quantity?: number
          color?: string | null
          piping_color?: string | null
          design_config?: Json
          has_embroidery?: boolean
          embroidery_name?: string | null
          embroidery_logo_url?: string | null
          special_instructions?: string | null
          status?: OrderStatus
          unit_price?: number | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      order_measurements: {
        Row: {
          id: string
          order_item_id: string
          customer_id: string
          product_type: ProductType
          chest: number | null
          waist: number | null
          hip: number | null
          shoulder: number | null
          sleeve_length: number | null
          body_length: number | null
          inseam: number | null
          neck: number | null
          head_circumference: number | null
          card_size: string | null
          custom_measurements: Json
          prefilled_from_profile: boolean
          notes: string | null
          measured_by: string | null
          measured_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_item_id: string
          customer_id: string
          product_type: ProductType
          chest?: number | null
          waist?: number | null
          hip?: number | null
          shoulder?: number | null
          sleeve_length?: number | null
          body_length?: number | null
          inseam?: number | null
          neck?: number | null
          head_circumference?: number | null
          card_size?: string | null
          custom_measurements?: Json
          prefilled_from_profile?: boolean
          notes?: string | null
          measured_by?: string | null
          measured_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_item_id?: string
          customer_id?: string
          product_type?: ProductType
          chest?: number | null
          waist?: number | null
          hip?: number | null
          shoulder?: number | null
          sleeve_length?: number | null
          body_length?: number | null
          inseam?: number | null
          neck?: number | null
          head_circumference?: number | null
          card_size?: string | null
          custom_measurements?: Json
          prefilled_from_profile?: boolean
          notes?: string | null
          measured_by?: string | null
          measured_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      customer_measurement_profiles: {
        Row: {
          id: string
          customer_id: string
          product_type: ProductType
          label: string
          chest: number | null
          waist: number | null
          hip: number | null
          shoulder: number | null
          sleeve_length: number | null
          body_length: number | null
          inseam: number | null
          neck: number | null
          head_circumference: number | null
          card_size: string | null
          custom_measurements: Json
          is_default: boolean
          notes: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          customer_id: string
          product_type: ProductType
          label?: string
          chest?: number | null
          waist?: number | null
          hip?: number | null
          shoulder?: number | null
          sleeve_length?: number | null
          body_length?: number | null
          inseam?: number | null
          neck?: number | null
          head_circumference?: number | null
          card_size?: string | null
          custom_measurements?: Json
          is_default?: boolean
          notes?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          customer_id?: string
          product_type?: ProductType
          label?: string
          chest?: number | null
          waist?: number | null
          hip?: number | null
          shoulder?: number | null
          sleeve_length?: number | null
          body_length?: number | null
          inseam?: number | null
          neck?: number | null
          head_circumference?: number | null
          card_size?: string | null
          custom_measurements?: Json
          is_default?: boolean
          notes?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      tailor_assignments: {
        Row: {
          id: string
          order_item_id: string
          tailor_id: string
          assigned_by: string
          assigned_at: string
          started_at: string | null
          completed_at: string | null
          estimated_hours: number | null
          actual_hours: number | null
          notes: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          order_item_id: string
          tailor_id: string
          assigned_by: string
          assigned_at?: string
          started_at?: string | null
          completed_at?: string | null
          estimated_hours?: number | null
          actual_hours?: number | null
          notes?: string | null
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          order_item_id?: string
          tailor_id?: string
          assigned_by?: string
          assigned_at?: string
          started_at?: string | null
          completed_at?: string | null
          estimated_hours?: number | null
          actual_hours?: number | null
          notes?: string | null
          is_active?: boolean
          created_at?: string
        }
        Relationships: []
      }
      embroidery_details: {
        Row: {
          id: string
          order_item_id: string
          assigned_to: string | null
          assigned_by: string | null
          assigned_at: string | null
          embroidery_type: string | null
          placement: string | null
          thread_colors: string[] | null
          logo_url: string | null
          name_text: string | null
          font_style: string | null
          special_instructions: string | null
          started_at: string | null
          completed_at: string | null
          status: 'pending' | 'in_progress' | 'completed' | 'rejected'
          rejection_reason: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_item_id: string
          assigned_to?: string | null
          assigned_by?: string | null
          assigned_at?: string | null
          embroidery_type?: string | null
          placement?: string | null
          thread_colors?: string[] | null
          logo_url?: string | null
          name_text?: string | null
          font_style?: string | null
          special_instructions?: string | null
          started_at?: string | null
          completed_at?: string | null
          status?: 'pending' | 'in_progress' | 'completed' | 'rejected'
          rejection_reason?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_item_id?: string
          assigned_to?: string | null
          assigned_by?: string | null
          assigned_at?: string | null
          embroidery_type?: string | null
          placement?: string | null
          thread_colors?: string[] | null
          logo_url?: string | null
          name_text?: string | null
          font_style?: string | null
          special_instructions?: string | null
          started_at?: string | null
          completed_at?: string | null
          status?: 'pending' | 'in_progress' | 'completed' | 'rejected'
          rejection_reason?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      order_status_history: {
        Row: {
          id: string
          order_id: string
          order_item_id: string | null
          from_status: OrderStatus | null
          to_status: OrderStatus
          changed_by: string
          reason: string | null
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          order_id: string
          order_item_id?: string | null
          from_status?: OrderStatus | null
          to_status: OrderStatus
          changed_by: string
          reason?: string | null
          metadata?: Json
          created_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          order_item_id?: string | null
          from_status?: OrderStatus | null
          to_status?: OrderStatus
          changed_by?: string
          reason?: string | null
          metadata?: Json
          created_at?: string
        }
        Relationships: []
      }
      media_attachments: {
        Row: {
          id: string
          order_id: string | null
          order_item_id: string | null
          media_type: MediaType
          file_name: string
          file_size_bytes: number
          mime_type: string
          storage_bucket: string
          storage_path: string
          public_url: string | null
          duration_seconds: number | null
          transcription: string | null
          uploaded_by: string
          created_at: string
        }
        Insert: {
          id?: string
          order_id?: string | null
          order_item_id?: string | null
          media_type: MediaType
          file_name: string
          file_size_bytes: number
          mime_type: string
          storage_bucket: string
          storage_path: string
          public_url?: string | null
          duration_seconds?: number | null
          transcription?: string | null
          uploaded_by: string
          created_at?: string
        }
        Update: {
          id?: string
          order_id?: string | null
          order_item_id?: string | null
          media_type?: MediaType
          file_name?: string
          file_size_bytes?: number
          mime_type?: string
          storage_bucket?: string
          storage_path?: string
          public_url?: string | null
          duration_seconds?: number | null
          transcription?: string | null
          uploaded_by?: string
          created_at?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          id: string
          recipient_id: string
          type: NotificationType
          title: string
          body: string
          data: Json
          is_read: boolean
          read_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          recipient_id: string
          type: NotificationType
          title: string
          body: string
          data?: Json
          is_read?: boolean
          read_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          recipient_id?: string
          type?: NotificationType
          title?: string
          body?: string
          data?: Json
          is_read?: boolean
          read_at?: string | null
          created_at?: string
        }
        Relationships: []
      }
      audit_logs: {
        Row: {
          id: string
          actor_id: string
          action: string
          resource_type: string
          resource_id: string
          before_state: Json | null
          after_state: Json | null
          ip_address: string | null
          user_agent: string | null
          created_at: string
        }
        Insert: {
          id?: string
          actor_id: string
          action: string
          resource_type: string
          resource_id: string
          before_state?: Json | null
          after_state?: Json | null
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          actor_id?: string
          action?: string
          resource_type?: string
          resource_id?: string
          before_state?: Json | null
          after_state?: Json | null
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      mv_tailor_performance: {
        Row: {
          tailor_id: string | null
          tailor_name: string | null
          active_assignments: number | null
          completed_assignments: number | null
          avg_hours_per_item: number | null
        }
      }
    }
    Functions: {
      search_orders: {
        Args: {
          search_term?: string
          status_filter?: string[]
          product_filter?: string[]
          tailor_filter?: string
          date_from?: string
          date_to?: string
          lim?: number
          off?: number
        }
        Returns: {
          id: string
          order_number: string
          customer_id: string
          status: string
          priority: number
          delivery_date: string | null
          total_items: number
          created_at: string
          updated_at: string
        }[]
      }
      auth_user_role: {
        Args: Record<string, never>
        Returns: string
      }
      get_overdue_orders: {
        Args: Record<string, never>
        Returns: {
          id: string
          order_number: string
          customer_id: string
          status: string
          delivery_date: string
        }[]
      }
      refresh_analytics: {
        Args: Record<string, never>
        Returns: undefined
      }
    }
    Enums: {
      user_role: UserRole
      order_status: OrderStatus
      product_type: ProductType
      media_type: MediaType
      notification_type: NotificationType
    }
    CompositeTypes: Record<string, never>
  }
}
